name: CleanConnect

on:
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: |
          python -m pip install --upgrade pip
          echo "Running compileall..."
          python -m compileall 
             
